services:
  restate:
    image: docker.restate.dev/restatedev/restate:1.7.2
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9071:9071"
    extra_hosts:
      - "host.docker.internal:host-gateway"
